version: '3.8'

services:
  # Web服务 - 提供前端界面
  web:
    image: nginx:alpine
    container_name: telegram-upload-web
    ports:
      - "80:80"  # 将容器80端口映射到主机80端口
    volumes:
      - ./web:/usr/share/nginx/html  # 挂载网页文件
      - ./config/nginx:/etc/nginx/conf.d  # 挂载Nginx配置
      - ./logs/nginx:/var/log/nginx  # 挂载Nginx日志
    restart: always
    networks:
      - telegram-network
    depends_on:
      - api

  # API服务 - 处理后端逻辑
  api:
    image: python:3.9-slim
    container_name: telegram-upload-api
    volumes:
      - ./data:/app/data  # 存储上传的文件
      - ./config:/app/config  # 存储应用配置
      - ./logs/api:/app/logs  # 存储API日志
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=info
    restart: always
    networks:
      - telegram-network
    command: >
      sh -c "pip install --no-cache-dir telegram-upload &&
             python -m telegram_upload.server --host 0.0.0.0 --port 5000"

networks:
  telegram-network:
    driver: bridge
